version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Instalamos dependencias
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Ejecutamos flake8 y pytest
          command: |
            . venv/bin/activate
            flake8 saludar.py
            pytest -v
